name = "IL_simulations"
uuid = "49fced47-e921-4857-8a02-882f78b9acba"
authors = ["viniciuspiccoli <viniciuspiccoli2008@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
ComplexMixtures = "6f35c628-ac57-5bae-8ea9-703a8964f6e9"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
ComplexMixtures = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
